when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            dsn: 'file:%kernel.project_dir%/var/profiler/%kernel.environment%'

when@test:
    framework:
        profiler:
            collect: false
            dsn: 'file:%kernel.project_dir%/var/profiler/%kernel.environment%'
